name: ML CI with Docker

on:
  push:
    branches: [ "main","develop" ]
  pull_request: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses : action/checkout@v4
      - name: Build Docker image
        run: docker build -t ml-quality
      - name: Run ML Container
        run: docker run ml-quality
        
