name: ML CI with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses : actions/checkout@v4
        
      - name: Train model
        run: |
          python - m pip install --upgrade pip
          pip install -r requirements.txt
          python train.py

      - name: Build Docker image
        run: docker build -t ml-quality .
        
      - name: Run ML prediction
        run: docker run ml-quality
        
